// Package bootnode implements the central bootnode for node registration,
// peer distribution, and block observability collection.
//
// The bootnode accepts connections, maintains the global node table,
// distributes peer assignments (pre-generated by the simulator), and
// collects all mined blocks to build the full block DAG.
// It does not mine or forward/validate blocks.
package bootnode

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"maps"
	"math"
	"net"
	"sort"
	"sync"
	"time"

	"github.com/stellashiina/pow-routine/config"
	"github.com/stellashiina/pow-routine/p2p"
	"github.com/stellashiina/pow-routine/report"
)

// Bootnode is the central bootstrap node.
type Bootnode struct {
	port      int
	listener  net.Listener
	peers     map[int]string // nodeID -> "ip:port"
	nodeConns map[int]net.Conn
	mu        sync.Mutex
	stopCh    chan struct{}
	startTime time.Time

	// Block storage (observability core)
	blockMu    sync.Mutex
	blocks     map[[32]byte]*p2p.BlockRepr // full block DAG: hash -> block
	blockCount int
	// Per-miner stats
	nodeBlockCount map[int]int // minerID -> count
	// Timeline of block arrival times
	blockTimeline []time.Time

	// PeersAssigned is closed once all peer assignments have been sent.
	PeersAssigned chan struct{}

	targetOnce sync.Once

	// Done is closed when target height is reached.
	Done chan struct{}

	// Ready is closed when the bootnode starts listening.
	Ready chan struct{}

	// peerAssignments maps each node to its assigned peers.
	peerAssignments map[int][]int
}

// NewBootnode creates a new Bootnode instance.
func NewBootnode(port int) *Bootnode {
	return &Bootnode{
		port:            port,
		peers:           make(map[int]string),
		nodeConns:       make(map[int]net.Conn),
		stopCh:          make(chan struct{}),
		Done:            make(chan struct{}),
		blocks:          make(map[[32]byte]*p2p.BlockRepr),
		nodeBlockCount:  make(map[int]int),
		blockTimeline:   make([]time.Time, 0, 10000),
		Ready:           make(chan struct{}),
		PeersAssigned:   make(chan struct{}),
		peerAssignments: make(map[int][]int),
	}
}

// Start begins listening on the configured port.
func (bn *Bootnode) Start() error {
	var err error
	addr := fmt.Sprintf("127.0.0.1:%d", bn.port)
	bn.listener, err = net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("bootnode listen %s: %w", addr, err)
	}
	bn.startTime = time.Now()
	slog.Info("[Bootnode] listening on", "Addr", addr)

	go bn.acceptLoop()
	close(bn.Ready)
	return nil
}

// Stop shuts down the bootnode.
func (bn *Bootnode) Stop() {
	close(bn.stopCh)
	if bn.listener != nil {
		bn.listener.Close()
	}
	bn.mu.Lock()
	for _, conn := range bn.nodeConns {
		conn.Close()
	}
	bn.mu.Unlock()
}

func (bn *Bootnode) acceptLoop() {
	for {
		conn, err := bn.listener.Accept()
		if err != nil {
			select {
			case <-bn.stopCh:
				return
			default:
				continue
			}
		}
		go bn.handleConn(conn)
	}
}

func (bn *Bootnode) handleConn(conn net.Conn) {
	defer conn.Close()
	for {
		msg, err := p2p.ReadMsg(conn)
		if err != nil {
			return
		}
		switch msg.Type {
		case p2p.MsgRegisterPayload:
			bn.handleRegister(conn, msg.Data)
		case p2p.MsgBlock:
			bn.handleBlockReport(msg.Data)
		default:
			slog.Warn("[Bootnode] unknown msg type", "MsgType", msg.Type)
		}
	}
}

func (bn *Bootnode) handleRegister(conn net.Conn, data json.RawMessage) {
	var reg p2p.RegisterPayload
	if err := json.Unmarshal(data, &reg); err != nil {
		slog.Warn("[Bootnode] bad register", "err", err)
		return
	}

	bn.mu.Lock()
	bn.peers[reg.NodeID] = reg.Addr
	bn.nodeConns[reg.NodeID] = conn
	totalNodes := len(bn.peers)
	bn.mu.Unlock()

	slog.Info("[Bootnode] registered node.", "NodeID", reg.NodeID, "NodeAddr", reg.Addr, "CurrentNodes", totalNodes, "config.NodeCount", config.NodeCount)

	// Send empty PeerList as registration ack; node will wait for MsgPeerAssignment.
	if err := p2p.SendMessage(conn, p2p.MsgPeerList, p2p.PeerList{Peers: nil}); err != nil {
		return
	}

	// Once all nodes are registered, generate and distribute peer assignments.
	if totalNodes == config.NodeCount {
		slog.Info("[Bootnode] all nodes registered, assigning peers...", "config.NodeCount", config.NodeCount)
		bn.assignAndDistributePeers()
	}
}

// assignAndDistributePeers randomly selects neighbors for each node
// and sends them via MsgPeerAssignment.
func (bn *Bootnode) assignAndDistributePeers() {
	bn.mu.Lock()
	defer bn.mu.Unlock()

	nodeIDs := make([]int, 0, len(bn.peers))
	for id := range bn.peers {
		nodeIDs = append(nodeIDs, id)
	}
	sort.Ints(nodeIDs)

	// Target peer count = ceil(Density * (NodeCount - 1)), at least 1.
	targetCount := int(math.Ceil(config.Density * float64(len(nodeIDs)-1)))
	if targetCount < 1 {
		targetCount = 1
	}
	if targetCount > len(nodeIDs)-1 {
		targetCount = len(nodeIDs) - 1
	}

	slog.Info("[Bootnode] target peers per node", "targetCount", targetCount, "density", config.Density, "nodes", len(nodeIDs))

	for _, nodeID := range nodeIDs {
		// Build candidate list (everyone except self).
		candidates := make([]int, 0, len(nodeIDs)-1)
		for _, other := range nodeIDs {
			if other != nodeID {
				candidates = append(candidates, other)
			}
		}

		// Shuffle and pick targetCount.
		config.RandSrc.Shuffle(len(candidates), func(i, j int) {
			candidates[i], candidates[j] = candidates[j], candidates[i]
		})

		assigned := make([]int, targetCount)
		copy(assigned, candidates[:targetCount])
		bn.peerAssignments[nodeID] = assigned

		peers := make([]p2p.PeerEntry, 0, len(assigned))
		for _, pid := range assigned {
			peers = append(peers, p2p.PeerEntry{
				NodeID: pid,
				Addr:   bn.peers[pid],
			})
		}

		conn := bn.nodeConns[nodeID]
		if err := p2p.SendMessage(conn, p2p.MsgPeerAssignment, p2p.PeerList{Peers: peers}); err != nil {
			slog.Warn("[Bootnode] send assignment to node failed", "NodeID", nodeID, "err", err)
		}
	}

	slog.Info("[Bootnode] peer assignments distributed to nodes", "nodes", len(nodeIDs))
	close(bn.PeersAssigned)
}

// SetGenesis injects the genesis block hash before simulation starts.
func (bn *Bootnode) SetGenesis(genesisHash [32]byte) {
	bn.blockMu.Lock()
	defer bn.blockMu.Unlock()
	bn.blocks[genesisHash] = &p2p.BlockRepr{
		Height:  0,
		MinerID: -1,
		Hash:    genesisHash,
		PreHash: [32]byte{},
		Arrived: bn.startTime,
	}
	bn.nodeBlockCount[-1] = 1 // genesis (not counted as a miner)
}

// handleBlockReport stores a reported block in the DAG and updates stats.
func (bn *Bootnode) handleBlockReport(data json.RawMessage) {
	var bp p2p.BlockPayload
	if err := json.Unmarshal(data, &bp); err != nil {
		return
	}

	now := time.Now()
	blk := &p2p.BlockRepr{
		Height:  bp.Height,
		MinerID: bp.MinerID,
		Hash:    bp.Hash,
		PreHash: bp.PreHash,
		Arrived: now,
	}

	bn.blockMu.Lock()
	// Dedup: keep only the first arrival per hash.
	if _, exists := bn.blocks[blk.Hash]; !exists {
		bn.blocks[blk.Hash] = blk
		bn.blockCount++
		bn.nodeBlockCount[blk.MinerID]++
		bn.blockTimeline = append(bn.blockTimeline, now)
	}
	count := bn.blockCount
	bn.blockMu.Unlock()

	if count > 0 && count%10 == 0 {
		elapsed := time.Since(bn.startTime).Seconds()
		slog.Info("[Bootnode] ⛓  total blocks mined:", "blocks", count, "blocks/sec", float64(count)/elapsed)
	}

	if bp.Height >= config.TargetHeight {
		bn.targetOnce.Do(func() {
			slog.Info("[Bootnode] 🎯  target height reached!", "height", config.TargetHeight, "NodeID", bp.NodeID)
			close(bn.Done)
		})
	}
}

// Stats returns the number of registered nodes and total blocks.
func (bn *Bootnode) Stats() (nodeCount int, blockCount int) {
	bn.mu.Lock()
	nodeCount = len(bn.peers)
	bn.mu.Unlock()
	bn.blockMu.Lock()
	blockCount = bn.blockCount
	bn.blockMu.Unlock()
	return
}

// WriteReport delegates to the report package to generate a full chain report.
func (bn *Bootnode) WriteReport() error {
	bn.blockMu.Lock()
	blocksCopy := bn.blocks
	bn.blockMu.Unlock()

	bn.mu.Lock()
	assignmentsCopy := make(map[int][]int, len(bn.peerAssignments))
	maps.Copy(assignmentsCopy, bn.peerAssignments)
	bn.mu.Unlock()

	return report.WriteChainReport(report.Input{
		StartTime:       bn.startTime,
		Blocks:          blocksCopy,
		PeerAssignments: assignmentsCopy,
	})
}

// WriteJSONReport writes a machine-readable snapshot alongside the text report.
func (bn *Bootnode) WriteJSONReport() error {
	bn.blockMu.Lock()
	blocksCopy := maps.Clone(bn.blocks)
	bn.blockMu.Unlock()

	bn.mu.Lock()
	assignmentsCopy := make(map[int][]int, len(bn.peerAssignments))
	for nodeID, peers := range bn.peerAssignments {
		assignmentsCopy[nodeID] = append([]int(nil), peers...)
	}
	bn.mu.Unlock()

	return report.WriteJSONReport(report.Input{
		StartTime:       bn.startTime,
		Blocks:          blocksCopy,
		PeerAssignments: assignmentsCopy,
	})
}

// Analyze returns a lightweight chain analysis summary.
func (bn *Bootnode) Analyze() (*report.ChainSummary, error) {
	bn.blockMu.Lock()
	blocksCopy := bn.blocks
	bn.blockMu.Unlock()

	return report.Analyze(blocksCopy)
}
