// Adjustable parameters:
//   - NodeCount:    Number of nodes
//   - Difficulty:   Mining difficulty (probability of successfully producing a block per attempt)
//   - Density:      P2P graph density (0–1); controls the proportion of neighboring nodes
//   - TargetHeight: Target block height at which the simulation terminates
//   - Seed:         Random seed (0 indicates no fixed seed; one will be generated by the system)
package config

import (
	"math/rand/v2"
)

var NodeCount int = 20

// value range (0, 1]
// In each iteration, every node attempts to obtain a random number uniformly distributed in the range [0, 1);
// if the value is less than the Difficulty, the block generation is considered successful.
var Difficulty float64 = 0.01

// value range (0, 1]。
// Each node establishes TCP connections with ceil(Density * (NodeCount - 1)) neighboring nodes.
var Density float64 = 0.5

// simulator stop when reaching this height
var TargetHeight int = 50

// seed to 0 to use random seed
var Seed uint64 = 42

var (
	// global random source
	RandSrc *rand.Rand

	// use to generate pseudo SHA256
	HashRandSrc *rand.ChaCha8
)

// if seed == 0, use random seed
func Init() {
	if Seed == 0 {
		s1 := rand.Uint64()
		s2 := rand.Uint64()
		RandSrc = rand.New(rand.NewPCG(s1, s2))
	} else {
		RandSrc = rand.New(rand.NewPCG(Seed, Seed+1))
	}
	// Derive a seed for HashRandSrc from RandSrc, ensuring the two are independent.
	// Note: *Rand from math/rand/v2 does not have a Read method, so we generate it manually here.
	var seed [32]byte
	for i := range 4 {
		val := RandSrc.Uint64()
		seed[i*8] = byte(val)
		seed[i*8+1] = byte(val >> 8)
		seed[i*8+2] = byte(val >> 16)
		seed[i*8+3] = byte(val >> 24)
		seed[i*8+4] = byte(val >> 32)
		seed[i*8+5] = byte(val >> 40)
		seed[i*8+6] = byte(val >> 48)
		seed[i*8+7] = byte(val >> 56)
	}
	HashRandSrc = rand.NewChaCha8(seed)
}

// Reset the random source (for reuse across multiple experiments).
func Reset() {
	Init()
}
